name: Build and Deploy Python (Django) App to Azure Web App - djnago-react-app-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Django App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          cd backend
          python manage.py collectstatic --noinput

      - name: Prepare deployment package
        run: |
          cd backend
          echo "python-3.12" > runtime.txt
          zip -r ../release.zip . -x "venv/*" "__pycache__/*" "*.pyc" "*.pyo"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'djnago-react-app-backend'   # your Azure Web App name
          package: release.zip
